name: Angular-CI

on: 
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js 16.1.0
      uses: actions/setup-node@v1
      with:
        node-version: '16.1.0'
    - name: Install dependencies
      run: npm install
    - name: install ionic
      run: npm install -g @ionic/cli
    - name: Eslint test
      run: npm run lint
    - name: Test
      run: npm run test:ci
    - name: Build
      run: npm run build:ci
