name: Angular-CI

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: cache node modules
      uses: actions/setup-node@v1
      with: 
        node-version: 16.1.0
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npx ng lint
    - name: Test
      run: npm test -- --configuration=ci
    - name: E2E
      run: npm run e2e -- --configuration=ci
    - name: Build
      run: npm run build -- --prod
